# Generated by Django 3.2.18 on 2023-03-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=80)),
                ('texto', models.CharField(max_length=300)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('gostei', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
